export type UiLang = "en" | "ar";

type Entry = { en: string; ar: string };

const dict: Record<string, Entry> = {
  paymentMethod: { en: "Method", ar: "الطريقة" },

  // Nav & shell
  dashboard: { en: "Dashboard", ar: "لوحة التحكم" },
  invoices: { en: "Invoices", ar: "الفواتير" },
  recurring: { en: "Recurring", ar: "المتكرر" },
  catalog: { en: "Catalog", ar: "المنتجات" },
  reports: { en: "Reports", ar: "التقارير" },
  clients: { en: "Clients", ar: "العملاء" },
  settings: { en: "Settings", ar: "الإعدادات" },
  signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  newInvoice: { en: "New invoice", ar: "فاتورة جديدة" },
  newClient: { en: "New client", ar: "عميل جديد" },

  // Common actions
  save: { en: "Save", ar: "حفظ" },
  saveChanges: { en: "Save changes", ar: "حفظ التغييرات" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  delete: { en: "Delete", ar: "حذف" },
  edit: { en: "Edit", ar: "تعديل" },
  create: { en: "Create", ar: "إنشاء" },
  add: { en: "Add", ar: "إضافة" },
  remove: { en: "Remove", ar: "إزالة" },
  close: { en: "Close", ar: "إغلاق" },
  search: { en: "Search", ar: "بحث" },
  loading: { en: "Loading…", ar: "جارٍ التحميل…" },
  saving: { en: "Saving…", ar: "جارٍ الحفظ…" },
  sending: { en: "Sending…", ar: "جارٍ الإرسال…" },
  copy: { en: "Copy", ar: "نسخ" },
  copied: { en: "Copied", ar: "تم النسخ" },
  preview: { en: "Preview PDF", ar: "معاينة PDF" },
  downloadPdf: { en: "Download PDF", ar: "تحميل PDF" },
  verifySignature: { en: "Verify signature", ar: "التحقق من التوقيع" },

  // Statuses
  status: { en: "Status", ar: "الحالة" },
  all: { en: "All", ar: "الكل" },
  sent: { en: "Sent", ar: "مرسل" },
  overdue: { en: "Overdue", ar: "متأخر" },
  paid: { en: "Paid", ar: "مدفوع" },
  draft: { en: "Draft", ar: "مسودة" },
  partiallyPaid: { en: "Partially paid", ar: "مدفوع جزئياً" },
  cancelled: { en: "Cancelled", ar: "ملغي" },

  // Dashboard
  snapshot: { en: "A snapshot of your invoicing health", ar: "نظرة على صحة فواتيرك" },
  outstanding: { en: "Outstanding", ar: "المستحق" },
  invoicedMonth: { en: "Invoiced this month", ar: "فوترة هذا الشهر" },
  collectedMonth: { en: "Collected this month", ar: "المحصّل هذا الشهر" },
  recentInvoices: { en: "Recent invoices", ar: "أحدث الفواتير" },
  viewAll: { en: "View all", ar: "عرض الكل" },
  outstandingByClient: { en: "Outstanding by client", ar: "المستحق حسب العميل" },
  openInvoices: { en: "open invoices", ar: "فاتورة مفتوحة" },
  fromPayments: { en: "from payments", ar: "من المدفوعات" },
  allCaughtUp: { en: "All caught up — nothing outstanding", ar: "كل شيء مدفوع — لا توجد مستحقات" },

  // Invoices
  invoiceNumber: { en: "Number", ar: "الرقم" },
  issueDate: { en: "Issue date", ar: "تاريخ الإصدار" },
  dueDate: { en: "Due date", ar: "تاريخ الاستحقاق" },
  total: { en: "Total", ar: "الإجمالي" },
  balance: { en: "Balance", ar: "المتبقي" },
  invoiceDetails: { en: "Invoice details", ar: "تفاصيل الفاتورة" },
  lineItems: { en: "Line items", ar: "بنود الفاتورة" },
  description: { en: "Description", ar: "الوصف" },
  quantity: { en: "Qty", ar: "الكمية" },
  unitPrice: { en: "Unit price", ar: "سعر الوحدة" },
  amount: { en: "Amount", ar: "المبلغ" },
  addLineItem: { en: "Add line item", ar: "إضافة بند" },
  documentType: { en: "Document type", ar: "نوع المستند" },
  invoice: { en: "Invoice", ar: "فاتورة" },
  quote: { en: "Quote", ar: "عرض سعر" },
  taxName: { en: "Tax name", ar: "اسم الضريبة" },
  taxRate: { en: "Tax rate (%)", ar: "نسبة الضريبة" },
  taxIncluded: { en: "Tax included in prices", ar: "الضريبة مضمنة في الأسعار" },
  discount: { en: "Discount", ar: "الخصم" },
  notes: { en: "Notes", ar: "ملاحظات" },
  sendInvoice: { en: "Send invoice", ar: "إرسال الفاتورة" },
  sendNow: { en: "Save and send (assigns number)", ar: "حفظ وإرسال (ترقيم تلقائي)" },
  createInvoice: { en: "Create invoice", ar: "إنشاء فاتورة" },
  shareEmail: { en: "Share & email", ar: "مشاركة وإرسال" },
  shareLink: { en: "Share link", ar: "رابط المشاركة" },
  viewAsClient: { en: "View as client", ar: "عرض كعميل" },
  convertToInvoice: { en: "Convert to invoice", ar: "تحويل إلى فاتورة" },
  convertToQuote: { en: "Convert to quote", ar: "تحويل إلى عرض سعر" },
  repeat: { en: "Repeat…", ar: "تكرار…" },
  cancelInvoice: { en: "Cancel invoice", ar: "إلغاء الفاتورة" },
  recordPayment: { en: "Record payment", ar: "تسجيل دفعة" },
  payments: { en: "Payments", ar: "المدفوعات" },
  summary: { en: "Summary", ar: "الملخص" },
  subtotal: { en: "Subtotal", ar: "المجموع الفرعي" },
  lateFee: { en: "Late fee", ar: "رسوم تأخير" },
  invoiceDocument: { en: "Invoice document", ar: "مستند الفاتورة" },
  invoiceDocHint: { en: "This exact layout is used for the PDF", ar: "هذا التخطيط هو نفسه المستخدم في ملف PDF" },
  searchNumberOrClient: { en: "Search number or client…", ar: "ابحث بالرقم أو العميل…" },
  noInvoices: { en: "No invoices found", ar: "لا توجد فواتير" },
  noInvoicesYet: { en: "No invoices yet", ar: "لا توجد فواتير بعد" },
  createFirstInvoice: { en: "Create your first invoice", ar: "أنشئ أول فاتورة" },
  signPdf: { en: "Sign PDF", ar: "توقيع PDF" },
  signing: { en: "Signing…", ar: "جارٍ التوقيع…" },
  signed: { en: "Signed", ar: "موقّعة" },
  ready: { en: "Ready", ar: "جاهزة" },
  notConfigured: { en: "Not configured", ar: "غير مهيأة" },
  signedPdf: { en: "Signed PDF", ar: "PDF موقّعة" },

  // Clients
  client: { en: "Client", ar: "العميل" },
  clientsSubtitle: { en: "clients", ar: "عملاء" },
  clientDetails: { en: "Client details", ar: "تفاصيل العميل" },
  nameEn: { en: "Name (primary)", ar: "الاسم (الأساسي)" },
  nameAr: { en: "Name in Arabic", ar: "الاسم بالعربية" },
  email: { en: "Email", ar: "البريد الإلكتروني" },
  phone: { en: "Phone", ar: "الهاتف" },
  addressEn: { en: "Address (primary)", ar: "العنوان (الأساسي)" },
  addressAr: { en: "Address in Arabic", ar: "العنوان بالعربية" },
  taxId: { en: "Tax / VAT ID", ar: "الرقم الضريبي" },
  defaultCurrency: { en: "Default currency", ar: "العملة الافتراضية" },
  invoiceLanguage: { en: "Invoice language", ar: "لغة الفاتورة" },
  paymentTerms: { en: "Payment terms (days)", ar: "مدة السداد (أيام)" },
  contactBilling: { en: "Contact & billing info", ar: "معلومات التواصل والفواتير" },
  searchClients: { en: "Search clients…", ar: "ابحث عن العملاء…" },
  noClients: { en: "No clients found", ar: "لا يوجد عملاء" },
  addFirstClient: { en: "Add your first client", ar: "أضف أول عميل" },
  noInvoicesForClient: { en: "No invoices for this client yet", ar: "لا توجد فواتير لهذا العميل بعد" },
  totalBilled: { en: "Total billed", ar: "إجمالي الفوترة" },

  // Settings
  settingsSubtitle: { en: "These defaults flow into every new invoice and the printed PDF", ar: "هذه الإعدادات تنطبق على كل فاتورة جديدة وملفات PDF" },
  organization: { en: "Organization", ar: "المؤسسة" },
  companyName: { en: "Company name (primary)", ar: "اسم الشركة (الأساسي)" },
  companyNameAr: { en: "Company name in Arabic", ar: "اسم الشركة بالعربية" },
  logo: { en: "Logo", ar: "الشعار" },
  upload: { en: "Upload", ar: "رفع" },
  removeLogo: { en: "Remove logo", ar: "إزالة الشعار" },
  numberingDefaults: { en: "Numbering & defaults", ar: "الترقيم والافتراضيات" },
  invoicePrefix: { en: "Invoice prefix", ar: "بادئة الفاتورة" },
  defaultTemplate: { en: "Default PDF template", ar: "قالب PDF الافتراضي" },
  numerals: { en: "Number style on Arabic invoices", ar: "نمط الأرقام في الفواتير العربية" },
  westernDigits: { en: "Western digits (123)", ar: "أرقام غربية (123)" },
  easternDigits: { en: "Eastern digits (١٢٣)", ar: "أرقام شرقية (١٢٣)" },
  hijriDates: { en: "Show Hijri dates on documents", ar: "إظهار التواريخ الهجرية في المستندات" },
  lateFeeLabel: { en: "Late fee (%)", ar: "رسوم تأخير (٪)" },
  lateFeeHint: { en: "One-time % of the outstanding amount on overdue invoices", ar: "نسبة مئوية لمرة واحدة من المبلغ المستحق على الفواتير المتأخرة" },
  reportCurrency: { en: "Report currency", ar: "عملة التقارير" },
  reportCurrencyHint: { en: "Used to convert totals on the dashboard", ar: "تُستخدم لتحويل الإجماليات في لوحة التحكم" },
  brandColor: { en: "Brand color", ar: "لون العلامة التجارية" },
  brandColorHint: { en: "Your accent color — applied to the UI and PDFs", ar: "لونك المميز — يُطبق على الواجهة وملفات PDF" },
  teamMembers: { en: "Team & members", ar: "الفريق والأعضاء" },
  saveSettings: { en: "Save settings", ar: "حفظ الإعدادات" },

  // Team
  team: { en: "Team", ar: "الفريق" },
  teamSubtitle: { en: "Invite teammates and control what each member can do", ar: "ادعُ زملاءك وتحكم بصلاحيات كل عضو" },
  inviteMember: { en: "Invite a member", ar: "دعوة عضو" },
  role: { en: "Role", ar: "الدور" },
  admin: { en: "Admin", ar: "مدير" },
  accountant: { en: "Accountant", ar: "محاسب" },
  viewer: { en: "Viewer", ar: "مشاهد" },
  members: { en: "Members", ar: "الأعضاء" },
  pendingInvites: { en: "Pending invites", ar: "دعوات معلقة" },
  changePassword: { en: "Change password", ar: "تغيير كلمة المرور" },
  currentPassword: { en: "Current password", ar: "كلمة المرور الحالية" },
  newPassword: { en: "New password (8+ chars)", ar: "كلمة المرور الجديدة (8+ أحرف)" },
  sendInvite: { en: "Send invite", ar: "إرسال الدعوة" },
  inviteLink: { en: "Invite link", ar: "رابط الدعوة" },
  you: { en: "(you)", ar: "(أنت)" },

  // Recurring
  recurringSubtitle: { en: "Set up once on any sent invoice — new invoices are generated automatically", ar: "أعد الضبط مرة واحدة على أي فاتورة مرسلة — تُنشأ الفواتير تلقائياً" },
  frequency: { en: "Frequency", ar: "التكرار" },
  every: { en: "Every", ar: "كل" },
  dayOfMonth: { en: "Day of month", ar: "يوم من الشهر" },
  nextInvoice: { en: "Next invoice", ar: "الفاتورة القادمة" },
  createSchedule: { en: "Create schedule", ar: "إنشاء الجدولة" },
  repeatInvoice: { en: "Repeat this invoice", ar: "تكرار هذه الفاتورة" },
  repeatHint: { en: "New invoices will be created automatically on this schedule.", ar: "سيتم إنشاء فواتير جديدة تلقائياً وفق هذا الجدول." },
  active: { en: "Active", ar: "نشطة" },
  paused: { en: "Paused", ar: "متوقفة" },
  weekly: { en: "Weekly", ar: "أسبوعي" },
  monthly: { en: "Monthly", ar: "شهري" },
  quarterly: { en: "Quarterly", ar: "ربع سنوي" },
  yearly: { en: "Yearly", ar: "سنوي" },

  // Auth
  welcomeBack: { en: "Welcome back", ar: "مرحباً بعودتك" },
  signInTo: { en: "Sign in to your invoicing workspace", ar: "سجّل الدخول إلى مساحة الفوترة الخاصة بك" },
  startInvoicing: { en: "Start invoicing", ar: "ابدأ الفوترة" },
  oneWorkspace: { en: "One workspace for clients, invoices, and payments — in English and Arabic", ar: "مساحة واحدة للعملاء والفواتير والمدفوعات — بالإنجليزية والعربية" },
  signIn: { en: "Sign in", ar: "تسجيل الدخول" },
  signingIn: { en: "Signing in…", ar: "جارٍ تسجيل الدخول…" },
  createAccount: { en: "Create account", ar: "إنشاء حساب" },
  creating: { en: "Creating…", ar: "جارٍ الإنشاء…" },
  company: { en: "Company name", ar: "اسم الشركة" },
  yourName: { en: "Your name", ar: "اسمك" },
  workEmail: { en: "Work email", ar: "البريد الوظيفي" },
  password: { en: "Password", ar: "كلمة المرور" },
  noAccount: { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
  haveAccount: { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  createOne: { en: "Create one", ar: "أنشئ واحداً" },
};

export function u(key: string, lang: UiLang): string {
  const entry = dict[key];
  if (!entry) return key;
  return entry[lang];
}

export const UI_LANG_COOKIE = "ui-lang";
